/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.go.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.go.go.FuncDecl;
import org.xtext.example.go.go.GoPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Func Decl</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class FuncDeclImpl extends TopLevelDeclImpl implements FuncDecl
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FuncDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.FUNC_DECL;
  }

} //FuncDeclImpl
