/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.go.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Labeled Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.go.go.GoPackage#getLabeledStmt()
 * @model
 * @generated
 */
public interface LabeledStmt extends EObject
{
} // LabeledStmt
