/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.go.go;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Select Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.go.go.SelectStmt#getCommClause <em>Comm Clause</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.go.go.GoPackage#getSelectStmt()
 * @model
 * @generated
 */
public interface SelectStmt extends Statement
{
  /**
   * Returns the value of the '<em><b>Comm Clause</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.go.go.CommClause}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Comm Clause</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comm Clause</em>' containment reference list.
   * @see org.xtext.example.go.go.GoPackage#getSelectStmt_CommClause()
   * @model containment="true"
   * @generated
   */
  EList<CommClause> getCommClause();

} // SelectStmt
