/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.go.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.go.go.GoPackage#getSimpleStmt()
 * @model
 * @generated
 */
public interface SimpleStmt extends ForClause, Statement
{
} // SimpleStmt
