/**
 * generated by Xtext 2.14.0
 */
package org.xtext.example.go.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.go.ui.AbstractGoUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class GoUiModule extends AbstractGoUiModule {
  public GoUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
